# Generated by Django 4.2 on 2024-01-31 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Country', models.CharField(max_length=50)),
                ('Year', models.IntegerField()),
                ('Rank', models.CharField(max_length=50)),
                ('Total', models.FloatField()),
                ('S1', models.FloatField()),
                ('S2', models.FloatField()),
                ('C3', models.FloatField()),
                ('E3', models.FloatField()),
                ('E2', models.FloatField()),
                ('E1', models.FloatField()),
                ('P1', models.FloatField()),
                ('P2', models.FloatField()),
                ('P3', models.FloatField()),
                ('C1', models.FloatField()),
                ('C2', models.FloatField()),
                ('X1', models.FloatField()),
            ],
            options={
                'verbose_name': 'Data',
                'verbose_name_plural': 'Data',
            },
        ),
    ]
